---
- debug:
  msg: "{{ restart_web_server }}"
  tags:
    - php

- name: Ensure PHP packages are installed.
  yum:
    name: "{{ item }}"
    state: installed
  with_items: php_packages
  notify: restart-php-webserver
  tags:
    - php
