---
- name: Install base PHP packages
  apt: pkg={{ item }}
  with_items: php_packages
  tags:
    - php

- name: Install PHP extensions (modules)
  apt: pkg={{ item }}
  with_items: php_modules
  notify: restart-php-webserver
  changed_when: false
  tags:
    - php


- name: Enable extensions (modules) for all SAPI's
  command: php5enmod -s ALL {{ item }}
  when: ansible_distribution_major_version|int > 12
  changed_when: false
  with_items: php_modules
  tags:
    - php

#- name: Copy PHP settings files
#  template:
#    src=php.ini.j2
#    dest={{ item.value }}
#  with_dict: php_settings_pathes
#  notify: restart-php-webserver
