---
- name: Ensure PHP packages are installed Fedora < 22.
  yum:
    name: "{{ item }}"
    state: installed
  with_items: php_packages
  notify: restart-php-webserver
  when: ansible_distribution_major_version|int < 22
  tags:
    - php

- name: Ensure PHP packages are installed Fedora >= 22.
  shell: dnf install {{ item }} -y
  changed_when: false
  with_items: php_packages
  notify: restart-php-webserver
  when: ansible_distribution_major_version|int >= 22
  tags:
    - php


