---
# tasks file for ansible-php
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - php

- include: install-debian.yml
  when: "ansible_os_family == 'Debian'"
  tags:
    - php