---
# tasks file for ansible-php
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - php

- include: install-debian.yml
  when: "ansible_os_family == 'Debian'"
  tags:
    - php

- include: install-centos.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat'
  tags:
    - php

- include: install-fedora.yml
  when: ansible_distribution == "Fedora"
  tags:
    - php

- include: install-suse.yml
  when: ansible_distribution == 'SLES' or ansible_distribution == 'OES' or ansible_distribution == 'Suse' or ansible_distribution == 'openSUSE'
  tags:
    - php
